### ISSUE TITLE
Add author bio

### ISSUE THREAD

**Issue by spences10** [spences10/the-localhost-blog#103]
From looking at the Gatsby site it appears to use:

## `gatsby-config.js`

a mapping in the config:

https://github.com/gatsbyjs/gatsby/blob/829a2a091b/www/gatsby-config.js#L63

```js
  mapping: {
    "MarkdownRemark.frontmatter.author": `AuthorYaml`,
    "Mdx.frontmatter.author": `AuthorYaml`,
  },
```

Transformer yaml

```js
gatsby-transformer-yaml
```

## posts directory

an `author.yaml` file

https://github.com/gatsbyjs/gatsby/blob/829a2a091b/docs/blog/author.yaml

Example content:

```yaml
- id: Kyle Mathews
  bio: Founder @ GatsbyJS. Likes tech, reading/writing, founding things. Blogs at bricolage.io.
  avatar: avatars/kyle-mathews.jpeg
  twitter: "@kylemathews"
- id: Dustin Schau
  bio: Software Engineer @ GatsbyJS. Likes all things JavaScript, and travel. Doesn't totally suck 👋
  avatar: avatars/dustin-schau.png
  twitter: "@schaudustin"
```

## `gatsby-node.js`

Query `allAuthorsYaml` 

https://github.com/gatsbyjs/gatsby/blob/829a2a091b/www/gatsby-node.js#L414

```graphql
allAuthorYaml {
  edges {
    node {
      fields {
        slug
      }
    }
  }
}
```

## Blog post template

https://github.com/gatsbyjs/gatsby/blob/829a2a091b/www/src/templates/template-blog-post.js#L273

Initial ask: https://twitter.com/spences10/status/1216457749766209537?s=19
